### ISSUE TITLE
1050 issue when trying to export

### ISSUE THREAD

**Issue by Qiangong2** [LasseD/brickgraphics#12]
Whenever I try to export finished files, I get a 1050 error. the stacktrace is here:

```
Initiating components
Model file loaded
Created controllers after 725ms.
Created left view after 67ms.
Created right view after 76ms.
LDDMC main window operational after 112ms.
LDDMC main window operational after 959ms.
MainController initiated.
1050
java.lang.ArrayIndexOutOfBoundsException: 1050
	at building.Optimizer.setLdrawIdToLEGOColor(Optimizer.java:58)
	at building.Optimizer.<init>(Optimizer.java:32)
	at mosaic.io.LDRPrinter.buildWithPlatesFromTop(LDRPrinter.java:165)
	at mosaic.io.LDRPrinter.printTo(LDRPrinter.java:53)
	at mosaic.ui.actions.ExportLDR.saveLDR(ExportLDR.java:36)
	at mosaic.ui.actions.ExportLDR.actionPerformed(ExportLDR.java:46)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```
This also happens when you try to export to LDD

**Comment by LasseD** [comment]
Fixed in latest push to master. Please verify.

**Comment by Qiangong2** [comment]
Have you published the jar on your site? It seems like the same version as before

**Comment by LasseD** [comment]
The builds on c-mt.dk are updated now.

**Comment by Qiangong2** [comment]
Seems to be working now! closing...
